tool:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: greetingtool.cn4ee2iwicrv.eu-west-2.rds.amazonaws.com
    port: 3306
    database: greeting_tool
    username: admin
    password: 123