name: Maven Build and Deploy

on:
  push:
    branches: [ Backend-Dev ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests=true -f greeting-tool/server/pom.xml

    - name: Rename jar file
      run: mv greeting-tool/server/target/server-1.0-SNAPSHOT.jar greeting-tool/server/target/greetingtool.jar

    - name: SCP to Remote Server
      uses: appleboy/scp-action@master
      with:
        host: ec2-18-130-196-224.eu-west-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        source: 'greeting-tool/server/target/greetingtool.jar'
        target: '~/home/ec2-user/greetingtool/greetingtool.jar'

    - name: SSH into Remote Server and Run Jar
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-130-196-224.eu-west-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          pkill -f 'java -jar ~/home/ec2-user/greetingtool/greetingtool.jar' || true 
          cd ~/home/ec2-user/greetingtool/          # nohup java -jar greetingtool.jar > app.log 2>&1 &
